"""criação da tabela call_records

Revision ID: 340a71b6c344
Revises: 
Create Date: 2022-04-06 09:42:38.122406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "340a71b6c344"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "call_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("destination", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint('length("source") = 9', name="regra_check_source"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("call_records")
    # ### end Alembic commands ###
