"""added column api_key

Revision ID: 37ddb681a331
Revises: 9578a48997bc
Create Date: 2022-04-19 09:39:10.048912
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ddb681a331'
down_revision = '9578a48997bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###
