"""removed column unsafe_password

Revision ID: 9578a48997bc
Revises: ed72b72eae48
Create Date: 2022-04-19 09:25:29.827500
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9578a48997bc'
down_revision = 'ed72b72eae48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'unsafe_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'unsafe_password',
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
