"""adicionada tabela invoices 1:1 com orders

Revision ID: 92edb2aca82f
Revises: d377288ef72a
Create Date: 2022-04-12 09:30:15.567565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92edb2aca82f'
down_revision = 'd377288ef72a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=63), nullable=True),
    sa.Column('release_time', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('invoice_id'),
    sa.UniqueConstraint('invoice_number'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    # ### end Alembic commands ###
